name: GitHub Actions
run-name: Android

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  Build-Android-example:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.4.2'

      - name: Check out ImGui repository
        uses: actions/checkout@v6
        with:
          repository: ocornut/imgui
          show-progress: false
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v6
        with:
          show-progress: false
          path: CMakeForImGui

      - name: Configure
        run: |
          cd ${{ github.workspace }}/CMakeForImGui
          cmake -G FASTBuild -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui --preset Android

      - name: Build
        run: |
          cd ${{ github.workspace }}/CMakeForImGui
          cmake --build --preset Android

      - name: Upload
        uses: actions/upload-artifact@v7

        with:
          name: Example_Android_OpenGL3
          path: ${{ github.workspace }}/imgui/examples/example_android_opengl3/android/app/build/outputs/apk

