name: GitHub Actions
run-name: ${{ github.actor }} is testing out ${{ github.repository }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/depandabot.yml'

jobs:
  Build-Android-example:
    runs-on: ubuntu-latest
    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.0'

      - name: Check out ImGui repository
        uses: actions/checkout@v4
        with:
          repository: ocornut/imgui
          show-progress: false
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: CMakeForImGui

      - name: Configure
        run: |
          cd ${{ github.workspace }}/CMakeForImGui
          cmake -DIMGUI_SOURCE_DIR=${{ github.workspace }}/imgui --preset Android

      - name: Build
        run: |
          cd ${{ github.workspace }}/CMakeForImGui
          cmake --build --preset Android

      - name: Upload
        uses: actions/upload-artifact@v4

        with:
          name: Example_Android_OpenGL3
          path: ${{ github.workspace }}/imgui/examples/example_android_opengl3/android/app/build/outputs/apk

