name: GitHub Actions
run-name: ${{ github.actor }} is testing out ${{ github.repository }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  Configure-Build-Install-Uninstall-Package-Upload:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-15
            - windows-latest

          include:
            - os: ubuntu-latest
              generator: 'Unix Makefiles'
              triplet: x64-linux

            - os: macos-15
              generator: 'Ninja Multi-Config'
              triplet: x64-osx

            - os: windows-latest
              generator: 'Visual Studio 17 2022'
              triplet: x64-windows

          tag:
            - v1.92.1
            - v1.92.0
            - v1.91.9
            - v1.91.8
            - v1.91.7
            - v1.91.6
            - v1.91.5
            - v1.91.4
            - v1.91.3
            - v1.91.2
            - v1.91.1
            - v1.91.0
            - v1.90.9
            - v1.90.8
            - v1.90.7
            - v1.90.6
            - v1.90.5
            - v1.90.4
            - v1.90.3
            - v1.90.2
            - v1.90.1
            - v1.90
            - v1.89.9
            - v1.89.8
            - v1.89.7
            - v1.89.6
            - v1.89.3
            - v1.89.2
            - v1.89.1
            - v1.89
            - v1.88
            - v1.87
            - v1.86
            - v1.84
            - v1.83
            - v1.82
            - v1.81
            - v1.80

          build-type:
            - Debug

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Triggered by ${{ github.event_name }} on ${{ github.repository }} using ${{ github.ref}} branch and running on ${{ runner.os }}."

      - name: Install required packages on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --fix-missing libxinerama-dev libxcursor-dev mesa-common-dev xorg-dev libglu1-mesa-dev pkg-config libltdl-dev

      - name: Install required packages on macOS
        if: matrix.os == 'macos-15'
        run: brew install --cask xquartz

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.0'

      - name: Check out ImGui repository
        uses: actions/checkout@v4
        with:
          repository: ocornut/imgui
          show-progress: false
          ref: ${{ matrix.tag }}
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: CMakeForImGui

      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}/CMakeForImGui/.github/workflows
          triplet: ${{ matrix.triplet }}
          token: ${{ github.token }}

      - name: Configure
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          -G "${{ matrix.generator }}"
          -D VCPKG_MANIFEST_MODE=ON
          -D VCPKG_MANIFEST_DIR=${{ github.workspace }}/CMakeForImGui/.github/workflows
          -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/install.in.here
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -D install=ON
          -D install_examples=ON
          -D uninstall=ON
          -D misc=ON -D misc_freetype=ON -D misc_cpp=ON -D misc_debugger=ON -D misc_fonts=ON
          -D pkg-config=ON
          -D allegro5=ON
          -D glut=ON
          -D glfw=ON
          -D opengl2=ON
          -D opengl3=ON
          -D vulkan=ON
          -D sdl2=ON
          -D sdlrenderer2=ON
          -D sdl3=ON
          -D sdlrenderer3=ON
          -D sdlgpu3=ON
          -D examples=ON
          -D example_null=ON
          -D example_glfw_opengl2=ON -D example_glfw_opengl3=ON -D example_glfw_vulkan=ON
          -D example_sdl2_opengl2=ON -D example_sdl2_opengl3=ON -D example_sdl2_vulkan=ON
          -D example_sdl3_opengl3=ON -D example_sdl3_vulkan=ON
          -D example_sdl3_sdlgpu3=ON
          -D example_sdl2_sdlrenderer2=ON
          -D example_sdl3_sdlrenderer3=ON
          -D example_glut_opengl2=ON
          -D example_allegro5=OFF
          --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Extra configurations for macOS
        if: matrix.os == 'macos-15'
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          -D metal=ON
          -D osx=ON

      - name: Extra configurations for Windows
        if: matrix.os == 'windows-latest'
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          -D win32=ON
          -D dx9=ON
          -D dx10=ON
          -D dx11=ON
          -D dx12=ON
          -D example_win32_opengl3=ON
          -D example_win32_vulkan=ON
          -D example_win32_directx9=ON
          -D example_win32_directx10=ON
          -D example_win32_directx11=ON
          -D example_win32_directx12=ON
          -D example_sdl2_directx11=ON

      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ matrix.build-type }}

      - name: Fix install paths on Windows
        if: matrix.os == 'windows-latest'
        run: >
          (Get-Content -Path "${{ github.workspace }}\\build\\cmake_install.cmake")
          | ForEach-Object {$_ -replace 'D:\\a\\CMakeForImGui\\', 'D:/a/CMakeForImGui/'}
          | Set-Content -Path "${{ github.workspace }}\\build\\cmake_install.cmake"

      - name: Install
        run: >
          cmake
          --install ${{ github.workspace }}/build
          --config ${{ matrix.build-type }}

      - name: Uninstall
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --target uninstall

      - name: Package
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --target package
          --config ${{ matrix.build-type }}

      - name: Upload
        uses: actions/upload-artifact@v4

        with:
          name: build.imgui-${{ matrix.tag }}.${{ matrix.os }}.${{ matrix.triplet }}.${{ matrix.build-type }}
          path: ${{ github.workspace }}/build/package

      - run: echo "Job exited by ${{ job.status }}."

  Build-Android-example:
    runs-on: ubuntu-latest
    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.0'

      - name: Check out ImGui repository
        uses: actions/checkout@v4
        with:
          repository: ocornut/imgui
          show-progress: false
          ref: v1.92.1
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: CMakeForImGui

      - name: Configure
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -D android=OFF
          -D opengl3=OFF
          -D examples=OFF
          -D example_android_opengl3=OFF
          --toolchain ${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake

      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build

      - name: Upload
        uses: actions/upload-artifact@v4

        with:
          name: example_android_opengl3
          path: ${{ github.workspace }}/imgui/examples/example_android_opengl3/android/app/build/outputs/apk

