name: GitHub Actions
run-name: ${{ github.actor }} is testing out ${{ github.repository }}

on: [push]

jobs:
  Configure-Build-Install:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Triggered by ${{ github.event_name }} on ${{ github.repository }} using ${{ github.ref}} branch and running on ${{ runner.os }}."

      - name: ls
        run: |
          pwd
          ls ${{ github.workspace }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.0'

      - name: CMake version
        run: cmake --version

      - name: Check out CMakeForImGui
        uses: actions/checkout@v4
        with:
          path: CMakeForImGui

      - name: ls
        run: |
          pwd
          ls ${{ github.workspace }}

      - name: Check out ImGui repository
        uses: actions/checkout@v4
        with:
          repository: ocornut/imgui
          fetch-depth: 0
          fetch-tags: true
          show-progress: false
          path: imgui

      - name: ls
        run: |
          pwd
          ls ${{ github.workspace }}

      - name: Configure
        run: >
          cmake
          -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/installing.in.here
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -S ${{ github.workspace }}/CMakeForImGui
          -B build

      - name: Build
        run: cmake --build build --config Debug

      - name: Set install path on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: cmake -D CMAKE_INSTALL_PREFIX=D:/a/CMakeForImGui/CMakeForImGui/installing.in.here -S ${{ github.workspace }}/CMakeForImGui -B build

      - name: Install
        run: cmake --install build --config Debug

      - run: echo "Job exited by ${{ job.status }}."

