name: GitHub Actions
run-name: ${{ github.actor }} is testing out ${{ github.repository }}

on: [push]

jobs:
  Configure-Build-Install:
    strategy:
      matrix:
          os:
            - ubuntu-latest
          tag:
            - master

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Triggered by ${{ github.event_name }} on ${{ github.repository }} using ${{ github.ref}} branch and running on ${{ runner.os }}."

      - name: ls
        run: |
          pwd
          ls ${{ github.workspace }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.0'

      - name: CMake version
        run: cmake --version

      - name: Check out ImGui repository
        uses: actions/checkout@v4
        with:
          repository: ocornut/imgui
          show-progress: false
          ref: ${{ matrix.tag }}
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v4
        with:
          path: CMakeForImGui

      - name: Install required dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install --assume-yes --fix-missing libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libltdl-dev

      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}/CMakeForImGui/.github/workflows
          triplet: x64-linux
          token: ${{ github.token }}

      - name: Configure
        run: >
          cmake
          -D VCPKG_MANIFEST_MODE=ON
          -D VCPKG_MANIFEST_DIR=${{ github.workspace }}/CMakeForImGui/.github/workflows
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -D with_miscellaneous=ON -D misc_freetype=ON -D misc_cpp=ON -D misc_debugger=ON -D misc_cpp=ON
          -D pkg-config=ON
          -D glfw=ON
          -D opengl2=ON
          -D opengl3=ON
          -D vulkan=ON
          -D sdl2=ON
          -D sdl3=ON
          -D examples=ON
          -D example_null=ON
          -D example_glfw_opengl2=ON -D example_glfw_opengl3=ON -D example_glfw_vulkan=ON
          -D example_sdl2_opengl2=ON -D example_sdl2_opengl3=ON -D example_sdl2_vulkan=ON
          -D example_sdl3_opengl3=ON -D example_sdl3_vulkan=ON
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake


      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Debug

      - name: Get build artifacts
        uses: actions/upload-artifact@v4

        with:
          name: Get build directory
          path: ${{ github.workspace }}/build/

      - run: echo "Job exited by ${{ job.status }}."

