name: GitHub Actions
run-name: WebGPU backends Dawn, wgpu-native, WGVK

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  Configure-Build-Install-Uninstall-Package-Upload:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest

          include:
            - os: ubuntu-latest
              triplet: x64-linux

            - os: macos-latest
              triplet: arm64-osx

            - os: windows-latest
              triplet: x64-windows

          build-type:
            - Debug

          backend:
            - dawn
            - WGVK

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Triggered by ${{ github.event_name }} on ${{ github.repository }} using ${{ github.ref}} branch and running on ${{ runner.os }}."

      - name: Install required packages on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --fix-missing libxinerama-dev libxcursor-dev mesa-common-dev xorg-dev libglu1-mesa-dev pkg-config libltdl-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules libx11-xcb-dev autoconf autoconf-archive automake libtool

      - name: Install required packages on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install --cask xquartz
          brew install autoconf autoconf-archive automake libtool

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.4.2'

      - name: Check out ImGui repository
        uses: actions/checkout@v6
        with:
          repository: ocornut/imgui
          show-progress: false
          ref: master
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v6
        with:
          show-progress: false
          path: CMakeForImGui

      - name: Define VCPKG_ROOT env var as an alias to VCPKG_INSTALLATION_ROOT
        shell: bash
        run: echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v8
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}/CMakeForImGui
          triplet: ${{ matrix.triplet }}
          token: ${{ github.token }}

      - name: Configure WebGPU+Dawn and related examples
        if: matrix.backend == 'dawn'
        shell: bash
        run: |
          cd "${{ github.workspace }}/CMakeForImGui"

          cmake \
          -D IMGUI_SOURCE_DIR:PATH="${{ github.workspace }}/imgui" \
          -D CMAKE_BUILD_TYPE:STRING=${{ matrix.build-type }} \
          -D CMAKE_INSTALL_PREFIX:PATH="${{ github.workspace }}/install.in.here" \
          --preset Core

          cmake \
          -D VCPKG_INSTALL_OPTIONS:STRING=--x-feature=wgpu-dawn \
          -D DearImGui_Backend_WebGPU:BOOL=ON \
          -D IMGUI_IMPL_WEBGPU_BACKEND_DAWN:BOOL=ON \
          -D DearImGui_Backend_GLFW:BOOL=ON \
          -D Example_GLFW_WebGPU:BOOL=ON \
          -D DearImGui_Backend_SDL2:BOOL=ON \
          -D Example_SDL2_WebGPU:BOOL=ON \
          -D DearImGui_Backend_SDL3:BOOL=ON \
          -D Example_SDL3_WebGPU:BOOL=ON \
          -S . \
          -B build

      - name: Configure WebGPU+WGVK and related examples
        if: matrix.backend == 'WGVK'
        shell: bash
        run: |
          cd "${{ github.workspace }}/CMakeForImGui"

          git clone https://github.com/manuel5975p/WGVK.git

          cmake \
          -S WGVK \
          -B build \
          -D CMAKE_BUILD_TYPE:STRING=${{ matrix.build-type }} \
          -D CMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/wgvk-install

          cmake --build build
          cmake --install build --config ${{ matrix.build-type }}

          tree ${{ github.workspace }}/wgvk-install

          cmake -E rm -rf WGVK build

          cmake \
          -D IMGUI_SOURCE_DIR:PATH="${{ github.workspace }}/imgui" \
          -D CMAKE_BUILD_TYPE:STRING=${{ matrix.build-type }} \
          -D CMAKE_LIBRARY_PATH:PATH=${{ github.workspace }}/wgvk-install/lib \
          -D CMAKE_INCLUDE_PATH:PATH=${{ github.workspace }}/wgvk-install/include \
          -D CMAKE_INSTALL_PREFIX:PATH="${{ github.workspace }}/install.in.here" \
          --preset Core

          cmake \
          -D DearImGui_Backend_WebGPU:BOOL=ON \
          -D IMGUI_IMPL_WEBGPU_BACKEND_WGVK:BOOL=ON \
          -D DearImGui_Backend_GLFW:BOOL=ON \
          -D Example_GLFW_WebGPU:BOOL=ON \
          -D DearImGui_Backend_SDL2:BOOL=ON \
          -D Example_SDL2_WebGPU:BOOL=ON \
          -D DearImGui_Backend_SDL3:BOOL=ON \
          -D Example_SDL3_WebGPU:BOOL=ON \
          -S . \
          -B build

      - name: Build
        run: |
          cd "${{ github.workspace }}/CMakeForImGui"
          cmake --build build

      - name: Fix install paths on Windows
        if: matrix.os == 'windows-latest'
        run: >
          (Get-Content -Path "${{ github.workspace }}\\CMakeForImGui\\build\\cmake_install.cmake")
          | ForEach-Object {$_ -replace 'D:\\a\\CMakeForImGui\\', 'D:/a/CMakeForImGui/'}
          | Set-Content -Path "${{ github.workspace }}\\CMakeForImGui\\build\\cmake_install.cmake"

      - name: Install
        run: >
          cmake
          --build "${{ github.workspace }}/CMakeForImGui/build"
          --target install
          --config ${{ matrix.build-type }}

      - name: Uninstall
        run: >
          cmake
          --build "${{ github.workspace }}/CMakeForImGui/build"
          --target uninstall

      - name: Package
        run: >
          cmake
          --build "${{ github.workspace }}/CMakeForImGui/build"
          --target package
          --config ${{ matrix.build-type }}

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: build.imgui-master.WebGPU_Backend_With_${{ matrix.backend }}.${{ matrix.os }}.${{ matrix.triplet }}.${{ matrix.build-type }}
          path: ${{ github.workspace }}/CMakeForImGui/build/package

      - run: echo "Job exited by ${{ job.status }}."
